### PR TITLE
Use geo-types crate

### PR DESCRIPTION
**Pull request by groteworld**
As mentioned in #11 there is a new low dependency crate for geo types.

There seemed to be an issue with serde.Deserialize trait and the new geo-types.Point. Review should be done to let me know what this could hurt in the future.

### CODE REVIEW

**Comment by groteworld** [comment]
Error in question:
```
error[E0277]: the trait bound `geo_types::Point<T>: serde::Deserialize<'_>` is not satisfied
   --> src/opencage.rs:511:17
    |
511 | #[derive(Debug, Deserialize)]
    |                 ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `geo_types::Point<T>`
    |
    = note: required by `serde::de::SeqAccess::next_element`
```

**Comment by urschrei** [comment]
Ah, that's because serde's [optional](https://github.com/georust/rust-geo/blob/master/geo-types/Cargo.toml#L14) in geo-types. It's probably OK to leave it out for now – I tend to add `Deserialize` out of habit when it's available.

**Comment by groteworld** [comment]
> I tend to add Deserialize out of habit when it's available.

I hear you, just wanted to make sure we didn't have a specific reason. Thanks @urschrei!

**Pull request merged**
